App\Service\Search\Products\ObjectsForValidation\GlobalSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
      # soon will be defined
    location:
      - NotBlank: ~
      # soon will be defined
    reservationDate:
      - NotBlank: ~
      # soon will be defined
    reservationTime:
      - NotBlank: ~
      # soon will be defined

App\Service\Search\Products\ObjectsForValidation\RestaurantScopeSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    reservationTime:
      - NotBlank: ~
    restaurantName:
      - NotBlank: ~
    restaurantId:
      - NotBlank: ~

App\Entity\Reservation:
  properties:
    reservationTime:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    amountOfTime:
      - NotBlank: ~
      - Type: integer
        