App\Service\Search\Products\ObjectsForValidation\GlobalSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
      # soon will be defined
    location:
      - NotBlank: ~
      # soon will be defined
    reservationDate:
      - NotBlank: ~
      # soon will be defined
    reservationTime:
      - NotBlank: ~
      # soon will be defined

App\Service\Search\Products\ObjectsForValidation\RestaurantScopeSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    reservationTime:
      - NotBlank: ~
    restaurantName:
      - NotBlank: ~
    restaurantId:
      - NotBlank: ~

App\Service\Search\Products\ObjectsForValidation\RestaurantGroupValidatorObject:
  properties:
    personAmount:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    reservationTime:
      - NotBlank: ~
    restaurantName:
      - NotBlank: ~
    location:
      - NotBlank: ~

 # USER

App\Service\Security\Authentication\Validation\Objects\User\SignUpUser:
  properties:
    password:
      - NotBlank: {message: "password should not be blank"}

    username:
      - NotBlank: {message: "username should not be blank"}

    firstName:
      - NotBlank: {message: "first name should not be blank"}

    lastName:
      - NotBlank: {message: "last name should not be blank"}


# VERIFICATION

App\Service\Security\Authentication\Validation\Objects\Verification\LessPropertyVerification:
  properties:
    username:
      - NotBlank: {message: "email is missing"}

    verificationCode:
      - NotBlank: {message: "verification code should not be blank"}


# COMMENT
App\Service\Security\Validation\Objects\Comment:
  properties:
    comment:
      - NotBlank: {message: "comment is missing"}


# RESERVATION
App\Service\Security\Validation\Objects\Reservation:
  properties:
    personAmount:
      - NotBlank: {message: "person amount should not be blank"}

    tableId:
      - NotBlank: {message: "table id should not be blank"}

    reservationTime:
      - NotBlank: {message: "reservation time amount should not be blank"}

    reservationDate:
      - NotBlank: {message: "reservation date should not be blank"}


# entity validation
App\Entity\Reservation:
  properties:
    reservationTime:
      - NotBlank: ~

    reservationDate:
      - NotBlank: ~

    amountOfTime:
      - NotBlank: {message: "amount of time should not be blank"}
      - Type: {type: int, message: "Amount of time should be an integer"}
