App\Service\Search\Products\ObjectsForValidation\GlobalSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
      # soon will be defined
    location:
      - NotBlank: ~
      # soon will be defined
    reservationDate:
      - NotBlank: ~
      # soon will be defined
    reservationTime:
      - NotBlank: ~
      # soon will be defined

App\Service\Search\Products\ObjectsForValidation\RestaurantScopeSearchObject:
  properties:
    personAmount:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    reservationTime:
      - NotBlank: ~
    restaurantName:
      - NotBlank: ~
    restaurantId:
      - NotBlank: ~

App\Service\Search\Products\ObjectsForValidation\RestaurantGroupValidatorObject:
  properties:
    personAmount:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    reservationTime:
      - NotBlank: ~
    restaurantName:
      - NotBlank: ~
    location:
      - NotBlank: ~

App\Entity\Reservation:
  properties:
    reservationTime:
      - NotBlank: ~
    reservationDate:
      - NotBlank: ~
    amountOfTime:
      - NotBlank: ~
      - Type: integer


 # user authentication objects

App\Service\Security\Authentication\Validation\Objects\User\SignUpUser:
  properties:
    password:
      - NotBlank: {message: "password should not be blank"}

    username:
      - NotBlank: {message: "username should not be blank"}

    firstName:
      - NotBlank: {message: "first name should not be blank"}

    lastName:
      - NotBlank: {message: "last name should not be blank"}

