# AUTHENTICATION
login:
  path: /authentication/login
  controller: App\Controller\SecurityController::login

sign_up:
  path: /authentication/sign-up
  controller: App\Controller\RegistrationController::getPage
  methods: [GET]

sign_up_post:
  path: /authentication/sign-up
  controller: App\Controller\RegistrationController::signUp
  methods: [POST]

# VERIFICATION
verification:
  path: /authentication/verification
  controller: App\Controller\VerificationController::getPage
  methods: [GET]

verification_post:
  path: /authentication/verification
  controller: App\Controller\VerificationController::verify
  methods: [POST]



# AJAX FUNCTIONALITY
bookmark:
  path: /restaurants/{restaurantId}/bookmark
  controller: App\Controller\BookmarkController::ajaxBookmark

comment:
  path: /restaurants/{restaurantId}/comment
  controller: App\Controller\CommentController::addComment

rating:
 path: /restaurants/{restaurantId}/rating
 controller: App\Controller\RatingController::addRating


user_page:
  path: /users/{user_id}
  controller: App\Controller\UserController::getUser

success:
  path: /success
  controller: App\Controller\SuccessController::showSuccessMessage

admin_page:
  path: /admin
  controller: App\Controller\AdminController::getPage

search:
  path: /search
  controller: App\Controller\SearchController::getResult

#reservation:
#  path: /reservation
#  controller: App\Controller\ReservationController::reserve

home_page:
  path: /home
  controller: App\Controller\HomeController::getPage

reservation:
  path: /restaurants/{restaurantName}/{restaurantId}/reservation
  controller: App\Controller\ReservationController::getPage
  methods: [GET]

make_reservation:
  path: /restaurants/{restaurantName}/{restaurantId}/reservation
  controller: App\Controller\ReservationController::reserve
  methods: [POST]

# concrete restaurant portion
restaurant:
  path: /restaurants/{restaurantName}/{restaurantId}
  controller: App\Controller\RestaurantController::getPage

test_for_ajax_search:
  path: /test
  controller: App\Controller\TestController::ajaxSearch

concrete_restaurant_reservation:
  path: /search/concrete-restaurant
  controller: App\Controller\ConcreteRestaurantReservationController::search

# restaurant group portion
restaurant_group:
  path: /restaurants/{restaurantName}
  controller: App\Controller\RestaurantGroupController::getPage

restaurant_group_search:
  path: /search/ajax/restaurant-group
  controller: App\Controller\RestaurantGroupController::ajaxSearch

restaurant_group_reservation:
  path: /search/restaurant-group
  controller: App\Controller\RestaurantGroupController::search


# DASHBOARD
dashboard:
  path: /me
  controller: App\Controller\DashboardController::getPage

# TESTING
data_preparing:
  path: /client/data
  controller: App\Controller\TestController::getRequiredData
