search:
  behavior: 'seems you know how to change html'
  timeAndDate: 'Set time and date reservation properly'
  reservingPast: 'We apologize, but time machine is unreal'

reservation:
  tableId: 'tableId is missing'

email:
  wrong_format: 'Given email address has wrong format'
  already_in_use: 'Given email address already in use'