restaurant:
  comment: 'comment'
  rating: 'rating'
  bookmark: 'bookmark'
  restaurant: 'restaurant'

reservation:
  reservationDate: 'reservationDate'
  reservationTime: 'reservationTime'

table:
  personAmount: 'personAmount'
  tableId: 'tableId'