restaurant:
  comment: 'comment'
  rating: 'rating'
  bookmark: 'bookmark'
  restaurant: 'restaurant'

reservation:
  reservationDate: 'reservationDate'
  reservationTime: 'reservationTime'
  amountOfTime: 'amountOfTime'

table:
  personAmount: 'personAmount'
  tableId: 'tableId'

auth:
  password: 'password'
  username: 'username'