search:
  behavior: 'behavior'
  location: 'location'
  personAmount: 'personAmount'
  reservationTime: 'reservationTime'
  reservationDate: 'reservationDate'
  restaurantName: 'restaurantName'
  restaurantId: 'restaurantId'

reservation:
  tableId: 'tableId'
  amountOfTime: 'amountOfTime'

postArray:
  reviewValue: 'reviewValue'