verification:
  verificationCode: "verificationCode"

navBar:
  search:
    personAmount: 'arrayOfPersonAmounts'
    cities: 'cities'

  user:
    user: 'user'


rating:
  review: 'review'
  restaurantRating: 'restaurantRating'


notification:
  notificationData: 'notificationData'